name: Go Build and Test CLI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies
      working-directory: starboard
      run: |
        go get -v -t -d ./...

    - name: Build
      working-directory: starboard
      run: |
        go generate
        go build -v .

    - name: Test
      working-directory: starboard
      run: go test -v .
